from PyQt5 import QtCore, QtGui, QtWidgets
from tsp_route import *
 
class Ui_MainWindow(object):
   def setupUi(self, MainWindow):
       MainWindow.setObjectName("TSP")
       MainWindow.resize(1000, 550)
       MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
       MainWindow.setMaximumSize(QtCore.QSize(5000, 5000))
       MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
       self.centralwidget = QtWidgets.QWidget(MainWindow)
       self.centralwidget.setObjectName("centralwidget")
       self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
       self.gridLayout.setObjectName("gridLayout")
       self.MaxSpeed = QtWidgets.QDoubleSpinBox(self.centralwidget)
       self.MaxSpeed.setMinimumSize(QtCore.QSize(0, 70))
       self.MaxSpeed.setAlignment(QtCore.Qt.AlignCenter)
       self.MaxSpeed.setAccelerated(True)
       self.MaxSpeed.setDecimals(1)
       self.MaxSpeed.setMaximum(15.0)
       self.MaxSpeed.setProperty("value", 5.0)
       self.MaxSpeed.setObjectName("MaxSpeed")
       self.gridLayout.addWidget(self.MaxSpeed, 1, 0, 1, 1)
       self.NoStations = QtWidgets.QComboBox(self.centralwidget)
       self.NoStations.setMinimumSize(QtCore.QSize(0, 70))
       self.NoStations.setCurrentText("")
       self.NoStations.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
       self.NoStations.setObjectName("NoStations")
       self.gridLayout.addWidget(self.NoStations, 2, 0, 1, 1)
       self.label_3 = QtWidgets.QLabel(self.centralwidget)
       self.label_3.setAlignment(QtCore.Qt.AlignCenter)
       self.label_3.setObjectName("label_3")
       self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
       self.label = QtWidgets.QLabel(self.centralwidget)
       self.label.setScaledContents(False)
       self.label.setAlignment(QtCore.Qt.AlignCenter)
       self.label.setObjectName("label")
       self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
       self.label_2 = QtWidgets.QLabel(self.centralwidget)
       self.label_2.setMinimumSize(QtCore.QSize(100, 20))
       self.label_2.setAlignment(QtCore.Qt.AlignCenter)
       self.label_2.setObjectName("label_2")
       self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
       self.UserSpeed = QtWidgets.QDoubleSpinBox(self.centralwidget)
       self.UserSpeed.setMinimumSize(QtCore.QSize(0, 70))
       self.UserSpeed.setAlignment(QtCore.Qt.AlignCenter)
       self.UserSpeed.setAccelerated(True)
       self.UserSpeed.setDecimals(1)
       self.UserSpeed.setMaximum(25.0)
       self.UserSpeed.setMinimum(0.1)
       self.UserSpeed.setProperty("value", 5.0)
       self.UserSpeed.setObjectName("UserSpeed")
       self.gridLayout.addWidget(self.UserSpeed, 0, 0, 1, 1)
       self.FindRoute = QtWidgets.QPushButton(self.centralwidget)
       self.FindRoute.setMinimumSize(QtCore.QSize(0, 70))
       self.FindRoute.setCheckable(False)
       self.FindRoute.setAutoDefault(False)
       self.FindRoute.setAutoRepeatDelay(5000)
       self.FindRoute.setObjectName("FindRoute")
       self.gridLayout.addWidget(self.FindRoute, 4, 0, 1, 1)
       self.CalculationSpeed = QtWidgets.QComboBox(self.centralwidget)
       self.CalculationSpeed.setMinimumSize(QtCore.QSize(0, 70))
       self.CalculationSpeed.setCurrentText("")
       self.CalculationSpeed.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
       self.CalculationSpeed.setObjectName("CalculationSpeed")
       self.gridLayout.addWidget(self.CalculationSpeed, 3, 0, 1, 1)
       self.label_4 = QtWidgets.QLabel(self.centralwidget)
       self.label_4.setAlignment(QtCore.Qt.AlignCenter)
       self.label_4.setObjectName("label_4")
       self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
       self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
       self.radioButton.setMaximumSize(QtCore.QSize(200, 16777215))
       self.radioButton.setObjectName("radioButton")
       self.gridLayout.addWidget(self.radioButton, 4, 1, 1, 1)
       MainWindow.setCentralWidget(self.centralwidget)
 
       self.retranslateUi(MainWindow)
       QtCore.QMetaObject.connectSlotsByName(MainWindow)
 
       self.FindRoute.clicked.connect(lambda: tsp_route(self.UserSpeed.value(), self.MaxSpeed.value(), self.NoStations.currentText(), self.CalculationSpeed.currentText(),self.radioButton.isChecked()))
 
 
   def retranslateUi(self, MainWindow):
       _translate = QtCore.QCoreApplication.translate
       MainWindow.setWindowTitle(_translate("MainWindow", "TSP"))
       self.label_3.setText(_translate("MainWindow", "Number of Stations"))
       self.label.setText(_translate("MainWindow", "User speed (MPH)"))
       self.label_2.setText(_translate("MainWindow", "Max Distance uesr can run (Miles)"))
       self.FindRoute.setText(_translate("MainWindow", "Find Route"))
       self.label_4.setText(_translate("MainWindow", "Calculation speed"))
       self.radioButton.setText(_translate("MainWindow", " Text output"))
